services:
  postgres:
    image: postgis/postgis:18-3.6
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-realtime_crowd_gis_db}
    # ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-realtime_crowd_gis_db}" ]
      interval: 10s
      timeout: 10s
      retries: 10

  martin:
    image: maplibre/martin:main
    environment:
      DATABASE_URL: postgresql://${DB_USER:-admin}:${DB_PASSWORD:-admin}@postgres:5432/${DB_NAME:-realtime_crowd_gis_db}
      MARTIN_POSTGRES_SCHEMA: public
    # ports:
    # - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  redis:
    image: redis:8.8-alpine
    # ports:
    #  - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-admin} --appendonly yes
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      # Identity
      KAFKA_CLUSTER_ID: "b8g1cnoNwj1eAy5LuEKjXw=="
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Controllers
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://kafka:29093,INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Replication
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    ports:
      - "8089:8081"
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - kafka
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local-dev-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG: "true"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rcg_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
      martin:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME:-realtime_crowd_gis_db}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-admin}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-admin}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - MARTIN_URL=http://martin:3000
      # Replace <IP_CUA_DROPLET> with the actual your IP address
      # - APP_FRONTEND_URL=http://<IP_CUA_DROPLET>
      # - APP_FRONTEND_OAUTH2_REDIRECT_URL=http://<IP_CUA_DROPLET>/auth/oauth2-redirect
      - APP_FRONTEND_OAUTH2_REDIRECT_URL=http://localhost/auth/oauth2-redirect
      - APP_FRONTEND_URL=http://localhost
      
      - APP_COOKIE_SECURE=${APP_COOKIE_SECURE:-false}
      - APP_COOKIE_SAMESITE=${APP_COOKIE_SAMESITE:-Lax}
      - SERVER_FORWARD_HEADERS_STRATEGY=framework

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rgc_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: