services:
  postgres:
    image: postgis/postgis:18-3.6
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-realtime_crowd_gis_db}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-realtime_crowd_gis_db}" ]
      interval: 10s
      timeout: 10s
      retries: 10

  martin:
    image: maplibre/martin:main
    environment:
      DATABASE_URL: postgresql://${DB_USER:-admin}:${DB_PASSWORD:-admin}@postgres:5432/${DB_NAME:-realtime_crowd_gis_db}
      MARTIN_POSTGRES_SCHEMA: public
    # ports:
    # - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  redis:
    image: redis:8.8-alpine
    # ports:
    #  - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-admin} --appendonly yes
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      # Identity
      KAFKA_CLUSTER_ID: "b8g1cnoNwj1eAy5LuEKjXw=="
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Controllers
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://kafka:29093,INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Replication
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    ports:
      - "8089:8081"
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - kafka
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local-dev-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG: "true"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rcg_backend
    restart: always
    ports:
      - "8088:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
      martin:
        condition: service_started
    environment:
      # --- DATABASE ---
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME:-realtime_crowd_gis_db}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-admin}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-admin}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

      # --- REDIS ---
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
      - SPRING_DATA_REDIS_LETTUCE_POOL_MAX_ACTIVE=16
      - SPRING_DATA_REDIS_LETTUCE_POOL_MAX_IDLE=8
      - SPRING_DATA_REDIS_LETTUCE_POOL_MIN_IDLE=4
      - SPRING_DATA_REDIS_LETTUCE_POOL_MAX_WAIT=200ms
      - SPRING_DATA_REDIS_LETTUCE_POOL_TIME_BETWEEN_EVICTION_RUNS=5m

      # --- KAFKA ---
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_KAFKA_PRODUCER_KEY_SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER=io.confluent.kafka.serializers.KafkaAvroSerializer
      - SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - SPRING_KAFKA_PRODUCER_PROPERTIES_AUTO_REGISTER_SCHEMAS=false
      - SPRING_KAFKA_PRODUCER_PROPERTIES_VALUE_SUBJECT_NAME_STRATEGY=io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
      - SPRING_KAFKA_PRODUCER_PROPERTIES_AVRO_USE_LOGICAL_TYPE_CONVERTERS=true
      - SPRING_KAFKA_PRODUCER_PROPERTIES_LINGER_MS=10
      - SPRING_KAFKA_PRODUCER_PROPERTIES_BATCH_SIZE=65536
      - SPRING_KAFKA_PRODUCER_ACKS=all
      - SPRING_KAFKA_PRODUCER_COMPRESSION_TYPE=snappy
      - SPRING_KAFKA_CONSUMER_GROUP_ID=crowd-gis-consumer-group
      - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER=io.confluent.kafka.serializers.KafkaAvroDeserializer
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SPECIFIC_AVRO_READER=true
      - SPRING_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT=false
      - SPRING_KAFKA_LISTENER_ACK_MODE=manual
      - SPRING_KAFKA_LISTENER_CONCURRENCY=3

      # --- MAIL SERVER ---
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED=true

      # --- GOOGLE OAUTH2 ---
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE=openid,email,profile

      # --- GOOGLE CLOUD STORAGE ---
      - APP_GCP_BUCKET_NAME=crowd-gis-reports-bucket
      - APP_GCP_PREFIX_URL=https://storage.googleapis.com
      - APP_GCP_CONFIG_FILE_PATH=file:/app/gcp-service-account.json

      # --- APP CUSTOM SETTINGS ---
      - APP_MARTIN_URL=http://martin:3000
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - APP_JWT_EXPIRATION_MS=${APP_JWT_EXPIRATION_MS:-86400000}
      - APP_JWT_REFRESH_EXPIRATION_DAYS=${APP_JWT_REFRESH_EXPIRATION_DAYS:-30}
      - APP_OTP_EXPIRATION_MINS=5
      - APP_OTP_ATTEMPTS_LIMIT=5

      # --- FRONTEND & SERVER ---
      - APP_FRONTEND_URL=${APP_FRONTEND_URL:-http://170.64.176.99}
      - APP_FRONTEND_OAUTH2_REDIRECT_URL=${APP_FRONTEND_OAUTH2_REDIRECT_URL:-http://170.64.176.99/auth/oauth2-redirect}
      - APP_COOKIE_SECURE=${APP_COOKIE_SECURE:-false}
      - APP_COOKIE_SAMESITE=${APP_COOKIE_SAMESITE:-Lax}
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=5MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=25MB
    volumes:
      - /root/gcp-service-account.json:/app/gcp-service-account.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rgc_frontend
    restart: always
    # ports:
    #   - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: