/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package me.gianghn.realtimecrowdgis.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class IncidentReportInProgressEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6193658460119305767L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IncidentReportInProgressEvent\",\"namespace\":\"me.gianghn.realtimecrowdgis.event\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"category\",\"type\":\"string\"},{\"name\":\"level\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"imageUrls\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"timestamp\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IncidentReportInProgressEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IncidentReportInProgressEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<IncidentReportInProgressEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<IncidentReportInProgressEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<IncidentReportInProgressEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this IncidentReportInProgressEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a IncidentReportInProgressEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a IncidentReportInProgressEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static IncidentReportInProgressEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private double latitude;
  private double longitude;
  private java.lang.CharSequence status;
  private java.lang.CharSequence category;
  private java.lang.CharSequence level;
  private java.lang.CharSequence description;
  private java.util.List<java.lang.CharSequence> imageUrls;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IncidentReportInProgressEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   * @param status The new value for status
   * @param category The new value for category
   * @param level The new value for level
   * @param description The new value for description
   * @param imageUrls The new value for imageUrls
   * @param timestamp The new value for timestamp
   */
  public IncidentReportInProgressEvent(java.lang.CharSequence id, java.lang.Double latitude, java.lang.Double longitude, java.lang.CharSequence status, java.lang.CharSequence category, java.lang.CharSequence level, java.lang.CharSequence description, java.util.List<java.lang.CharSequence> imageUrls, java.lang.Long timestamp) {
    this.id = id;
    this.latitude = latitude;
    this.longitude = longitude;
    this.status = status;
    this.category = category;
    this.level = level;
    this.description = description;
    this.imageUrls = imageUrls;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return latitude;
    case 2: return longitude;
    case 3: return status;
    case 4: return category;
    case 5: return level;
    case 6: return description;
    case 7: return imageUrls;
    case 8: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: latitude = (java.lang.Double)value$; break;
    case 2: longitude = (java.lang.Double)value$; break;
    case 3: status = (java.lang.CharSequence)value$; break;
    case 4: category = (java.lang.CharSequence)value$; break;
    case 5: level = (java.lang.CharSequence)value$; break;
    case 6: description = (java.lang.CharSequence)value$; break;
    case 7: imageUrls = (java.util.List<java.lang.CharSequence>)value$; break;
    case 8: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'category' field.
   * @return The value of the 'category' field.
   */
  public java.lang.CharSequence getCategory() {
    return category;
  }


  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(java.lang.CharSequence value) {
    this.category = value;
  }

  /**
   * Gets the value of the 'level' field.
   * @return The value of the 'level' field.
   */
  public java.lang.CharSequence getLevel() {
    return level;
  }


  /**
   * Sets the value of the 'level' field.
   * @param value the value to set.
   */
  public void setLevel(java.lang.CharSequence value) {
    this.level = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'imageUrls' field.
   * @return The value of the 'imageUrls' field.
   */
  public java.util.List<java.lang.CharSequence> getImageUrls() {
    return imageUrls;
  }


  /**
   * Sets the value of the 'imageUrls' field.
   * @param value the value to set.
   */
  public void setImageUrls(java.util.List<java.lang.CharSequence> value) {
    this.imageUrls = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new IncidentReportInProgressEvent RecordBuilder.
   * @return A new IncidentReportInProgressEvent RecordBuilder
   */
  public static me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder newBuilder() {
    return new me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder();
  }

  /**
   * Creates a new IncidentReportInProgressEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IncidentReportInProgressEvent RecordBuilder
   */
  public static me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder newBuilder(me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder other) {
    if (other == null) {
      return new me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder();
    } else {
      return new me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder(other);
    }
  }

  /**
   * Creates a new IncidentReportInProgressEvent RecordBuilder by copying an existing IncidentReportInProgressEvent instance.
   * @param other The existing instance to copy.
   * @return A new IncidentReportInProgressEvent RecordBuilder
   */
  public static me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder newBuilder(me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent other) {
    if (other == null) {
      return new me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder();
    } else {
      return new me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for IncidentReportInProgressEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IncidentReportInProgressEvent>
    implements org.apache.avro.data.RecordBuilder<IncidentReportInProgressEvent> {

    private java.lang.CharSequence id;
    private double latitude;
    private double longitude;
    private java.lang.CharSequence status;
    private java.lang.CharSequence category;
    private java.lang.CharSequence level;
    private java.lang.CharSequence description;
    private java.util.List<java.lang.CharSequence> imageUrls;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.category)) {
        this.category = data().deepCopy(fields()[4].schema(), other.category);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.level)) {
        this.level = data().deepCopy(fields()[5].schema(), other.level);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.description)) {
        this.description = data().deepCopy(fields()[6].schema(), other.description);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.imageUrls)) {
        this.imageUrls = data().deepCopy(fields()[7].schema(), other.imageUrls);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[8].schema(), other.timestamp);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing IncidentReportInProgressEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.category)) {
        this.category = data().deepCopy(fields()[4].schema(), other.category);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.level)) {
        this.level = data().deepCopy(fields()[5].schema(), other.level);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.description)) {
        this.description = data().deepCopy(fields()[6].schema(), other.description);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.imageUrls)) {
        this.imageUrls = data().deepCopy(fields()[7].schema(), other.imageUrls);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[8].schema(), other.timestamp);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setLatitude(double value) {
      validate(fields()[1], value);
      this.latitude = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearLatitude() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setLongitude(double value) {
      validate(fields()[2], value);
      this.longitude = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearLongitude() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategory() {
      return category;
    }


    /**
      * Sets the value of the 'category' field.
      * @param value The value of 'category'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setCategory(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.category = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'category' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearCategory() {
      category = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'level' field.
      * @return The value.
      */
    public java.lang.CharSequence getLevel() {
      return level;
    }


    /**
      * Sets the value of the 'level' field.
      * @param value The value of 'level'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setLevel(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.level = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'level' field has been set.
      * @return True if the 'level' field has been set, false otherwise.
      */
    public boolean hasLevel() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'level' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearLevel() {
      level = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.description = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearDescription() {
      description = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'imageUrls' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getImageUrls() {
      return imageUrls;
    }


    /**
      * Sets the value of the 'imageUrls' field.
      * @param value The value of 'imageUrls'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setImageUrls(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[7], value);
      this.imageUrls = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'imageUrls' field has been set.
      * @return True if the 'imageUrls' field has been set, false otherwise.
      */
    public boolean hasImageUrls() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'imageUrls' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearImageUrls() {
      imageUrls = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder setTimestamp(long value) {
      validate(fields()[8], value);
      this.timestamp = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public me.gianghn.realtimecrowdgis.event.IncidentReportInProgressEvent.Builder clearTimestamp() {
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IncidentReportInProgressEvent build() {
      try {
        IncidentReportInProgressEvent record = new IncidentReportInProgressEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.latitude = fieldSetFlags()[1] ? this.latitude : (java.lang.Double) defaultValue(fields()[1]);
        record.longitude = fieldSetFlags()[2] ? this.longitude : (java.lang.Double) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.category = fieldSetFlags()[4] ? this.category : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.level = fieldSetFlags()[5] ? this.level : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.description = fieldSetFlags()[6] ? this.description : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.imageUrls = fieldSetFlags()[7] ? this.imageUrls : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[7]);
        record.timestamp = fieldSetFlags()[8] ? this.timestamp : (java.lang.Long) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IncidentReportInProgressEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<IncidentReportInProgressEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IncidentReportInProgressEvent>
    READER$ = (org.apache.avro.io.DatumReader<IncidentReportInProgressEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

    out.writeString(this.status);

    out.writeString(this.category);

    out.writeString(this.level);

    out.writeString(this.description);

    long size0 = this.imageUrls.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.imageUrls) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

      this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);

      this.category = in.readString(this.category instanceof Utf8 ? (Utf8)this.category : null);

      this.level = in.readString(this.level instanceof Utf8 ? (Utf8)this.level : null);

      this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.imageUrls;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("imageUrls").schema());
        this.imageUrls = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.latitude = in.readDouble();
          break;

        case 2:
          this.longitude = in.readDouble();
          break;

        case 3:
          this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          break;

        case 4:
          this.category = in.readString(this.category instanceof Utf8 ? (Utf8)this.category : null);
          break;

        case 5:
          this.level = in.readString(this.level instanceof Utf8 ? (Utf8)this.level : null);
          break;

        case 6:
          this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          break;

        case 7:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.imageUrls;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("imageUrls").schema());
            this.imageUrls = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 8:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (id == null ? 0 : id.hashCode());
    result = 31 * result + Double.hashCode(latitude);
    result = 31 * result + Double.hashCode(longitude);
    result = 31 * result + (status == null ? 0 : status.hashCode());
    result = 31 * result + (category == null ? 0 : category.hashCode());
    result = 31 * result + (level == null ? 0 : level.hashCode());
    result = 31 * result + (description == null ? 0 : description.hashCode());
    result = 31 * result + (imageUrls == null ? 0 : imageUrls.hashCode());
    result = 31 * result + Long.hashCode(timestamp);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof IncidentReportInProgressEvent)) {
      return false;
    }
    IncidentReportInProgressEvent other = (IncidentReportInProgressEvent) o;
    if (Utf8.compareSequences(this.id, other.id) != 0) {
      return false;
    }
    if (this.latitude != other.latitude) {
      return false;
    }
    if (this.longitude != other.longitude) {
      return false;
    }
    if (Utf8.compareSequences(this.status, other.status) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.category, other.category) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.level, other.level) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.description, other.description) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.imageUrls, other.imageUrls)) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    return true;
  }
}










